module.exports = {
  apps: [
    {
      name: 'server',
      cwd: './apps/server',
      script: 'npm.cmd',
      args: 'run dev',
      env: {
        PORT: 3001,
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-server-error.log',
      out_file: './tmp/pm2-server-out.log',
      merge_logs: true,
      exec_mode: 'fork',
      kill_timeout: 5000,
    },
    {
      name: 'web',
      cwd: './apps/web',
      script: 'npm.cmd',
      args: 'run dev',
      env: {
        PORT: 3000,
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-web-error.log',
      out_file: './tmp/pm2-web-out.log',
      merge_logs: true,
      exec_mode: 'fork',
      kill_timeout: 5000,
    },
    {
      name: 'preview',
      cwd: './apps/preview',
      script: 'npm.cmd',
      args: 'run dev',
      env: {
        PORT: 3002,
        NODE_ENV: 'development',
        IN_PREVIEW_SERVER: 'true',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-preview-error.log',
      out_file: './tmp/pm2-preview-out.log',
      merge_logs: true,
      exec_mode: 'fork',
      kill_timeout: 5000,
    },
  ],
};
