module.exports = {
  apps: [
    {
      name: 'server',
      cwd: './apps/server',
      script: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
      args: 'run dev',
      env: {
        PORT: 3001,
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-server-error.log',
      out_file: './tmp/pm2-server-out.log',
      merge_logs: true,
      autorestart: true,
      watch: ['src'],
      ignore_watch: ['node_modules', 'workspace'],
      exec_mode: 'fork',
    },
    {
      name: 'web',
      cwd: './apps/web',
      script: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
      args: 'run dev',
      env: {
        PORT: 3000,
        NODE_ENV: 'development',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-web-error.log',
      out_file: './tmp/pm2-web-out.log',
      merge_logs: true,
      autorestart: true,
      watch: ['src'],
      ignore_watch: ['node_modules'],
      exec_mode: 'fork',
    },
    {
      name: 'preview',
      cwd: './apps/preview',
      script: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
      args: 'run dev',
      env: {
        PORT: 3002,
        NODE_ENV: 'development',
        IN_PREVIEW_SERVER: 'true',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './tmp/pm2-preview-error.log',
      out_file: './tmp/pm2-preview-out.log',
      merge_logs: true,
      autorestart: false,
      exec_mode: 'fork',
    },
  ],
};
