import { z } from 'zod';

/**
 * Zod schemas for channel types - single source of truth
 * Types are inferred from these schemas for runtime validation
 */

/**
 * Chat message schema - represents a single chat message
 * Used by the chat channel for message history and broadcasting
 */
const ChatMessageSchema = z.object({
  /**
   * Unique message identifier
   * Format: `msg-${timestamp}-${random}`
   */
  id: z.string(),

  /**
   * Message content text
   */
  content: z.string(),

  /**
   * User ID who sent the message
   */
  userId: z.string(),

  /**
   * Unix timestamp in milliseconds
   */
  timestamp: z.number(),
});

/**
 * Chat message type - inferred from schema
 */
export type ChatMessage = z.infer<typeof ChatMessageSchema>;

/**
 * Channel type registry - defines all available channels and their events
 * Separates client-to-server and server-to-client events
 *
 * Structure pattern:
 * ChannelTypes['channel-name'] = {
 *   client: { /* client -> server events * / };
 *   server: { /* server -> client events * / };
 * }
 */
export const ChannelTypesSchema = z.object({
  /**
   * Mock echo channel - for testing bidirectional communication
   * Client sends ping, server responds with pong
   */
  'mock:echo': z.object({
    client: z.object({
      'ping': z.object({ message: z.string() }),
    }),
    server: z.object({
      'pong': z.object({ message: z.string(), timestamp: z.number() }),
    }),
  }),

  /**
   * Mock status channel - for testing server-to-client only communication
   * Server sends status updates, client only receives
   */
  'mock:status': z.object({
    client: z.object({}),
    server: z.object({
      'update': z.object({ status: z.string() }),
    }),
  }),

  /**
   * Status channel - server-to-client only communication for AI generation status
   * Fire-and-forget: no history replay on reconnect
   */
  'status': z.object({
    client: z.object({}),
    server: z.object({
      'generation_start': z.object({ messageId: z.string(), details: z.string() }),
      'generation_thinking': z.object({ messageId: z.string(), details: z.string() }),
      'generation_complete': z.object({ messageId: z.string(), details: z.string() }),
      'tool_call_start': z.object({ messageId: z.string(), tool: z.string(), details: z.string() }),
      'tool_call_complete': z.object({ messageId: z.string(), tool: z.string(), details: z.string() }),
      'tool_call_error': z.object({ messageId: z.string(), tool: z.string(), details: z.string() }),
      'validation_start': z.object({ messageId: z.string(), details: z.string() }),
      'validation_complete': z.object({ messageId: z.string(), details: z.string() }),
      'preview_start': z.object({ messageId: z.string(), details: z.string() }),
      'preview_ready': z.object({ messageId: z.string(), port: z.number(), details: z.string() }),
      'preview_error': z.object({ messageId: z.string(), details: z.string() }),
    }),
  }),

  /**
   * Chat channel - bidirectional communication for chat messages
   * Client sends messages, server broadcasts to all subscribers
   * Includes message history on subscribe
   */
  'chat': z.object({
    client: z.object({
      'message': z.object({ content: z.string() }),
      'typing': z.object({ isTyping: z.boolean() }),
    }),
    server: z.object({
      'message': z.object({ content: z.string(), userId: z.string(), timestamp: z.number() }),
      'history': z.object({ messages: z.array(ChatMessageSchema) }),
      'user-joined': z.object({ userId: z.string(), name: z.string() }),
    }),
  }),
});

/**
 * Channel type registry - inferred from schema
 */
export type ChannelTypes = z.infer<typeof ChannelTypesSchema>;

/**
 * Helper type: Extract client-sent events for a channel
 */
export type ClientEvents<K extends keyof ChannelTypes> = ChannelTypes[K]['client'];

/**
 * Helper type: Extract server-sent events for a channel
 */
export type ServerEvents<K extends keyof ChannelTypes> = ChannelTypes[K]['server'];

/**
 * Payload schema (inside TransportEnvelope)
 * Validates structure: { event: string, data: unknown }
 */
export const PayloadSchema = z.object({
  event: z.string(),
  data: z.unknown(),
});

/**
 * Transport envelope schema - wraps payload with metadata for transport
 * Not exposed to application code
 */
export const TransportEnvelopeSchema = z.object({
  /**
   * Channel instance ID - unique per channel instance
   * Format: `channel-${sequence}` (server-generated incrementing counter)
   * Generated by server when onChannelSubscribe is called
   * Example: 'channel-1', 'channel-2', ...
   */
  channelId: z.string(),

  /**
   * Channel type from ChannelTypes
   * Used for routing to correct handler
   */
  channelType: z.string(),

  /**
   * Message ID - unique per channel instance
   * Format: `${sender}-msg-${sequence}` where sender is 'client' or 'server'
   * Generated by sender: incrementing counter per channel
   * Example: 'client-msg-1', 'server-msg-23'
   */
  messageId: z.string(),

  /**
   * Unix timestamp in milliseconds
   * Generated by sender: Date.now()
   */
  timestamp: z.number(),

  /**
   * Actual message payload
   */
  payload: PayloadSchema,
});

/**
 * Transport envelope type - inferred from schema
 */
export type TransportEnvelope = z.infer<typeof TransportEnvelopeSchema>;

/**
 * Control message schema - for subscription management
 * Note: No subscribe-ack - server uses queuing for flow control
 *
 * Protocol flow:
 * 1. Client sends 'subscribe' with channelType and requestId (temp channel ID)
 * 2. Server generates channelId and responds with 'subscribe-response' including the requestId
 * 3. Client matches requestId to the correct pending channel and updates its ID
 */
export const ControlMessageSchema = z.union([
  /**
   * Client requests subscription to channel type
   * Includes requestId (temp channel ID) for matching response
   * Server generates channelId and responds with 'subscribe-response'
   */
  z.object({
    type: z.literal('subscribe'),
    channelType: z.string(),
    requestId: z.string(),
  }),

  /**
   * Server responds with generated channelId
   * Echoes back the requestId so client can match to correct channel
   * Client uses assigned channelId for all subsequent messages
   */
  z.object({
    type: z.literal('subscribe-response'),
    channelType: z.string(),
    channelId: z.string(),
    requestId: z.string(),
  }),

  /**
   * Client unsubscribes from channel (explicit per-channel cleanup)
   */
  z.object({
    type: z.literal('unsubscribe'),
    channelId: z.string(),
  }),
]);

/**
 * Control message type - inferred from schema
 */
export type ControlMessage = z.infer<typeof ControlMessageSchema>;

/**
 * Client-side channel interface
 * - Can PUBLISH client events (to server)
 * - Can SUBSCRIBE to server events (from server)
 *
 * Note: This is an interface (not Zod) because it contains methods
 */
export interface Channel<T extends { client: Record<string, Record<string, unknown>>; server: Record<string, Record<string, unknown>> }> {
  /**
   * Subscribe to event from server
   */
  subscribe<K extends keyof T['server']>(
    event: K,
    handler: (payload: T['server'][K]) => void
  ): () => void;

  /**
   * Publish event to server
   */
  publish<K extends keyof T['client']>(
    event: K,
    payload: T['client'][K]
  ): Promise<void>;
}

/**
 * Return type for onChannelSubscribe callback
 * - handlers: All client event handlers (required, type-enforced)
 * - unsubscribe: Optional cleanup function
 *
 * Note: This is an interface (not Zod) because it contains method signatures
 */
export interface ChannelSubscription<T extends { client: Record<string, Record<string, unknown>> }> {
  /**
   * Handlers for all client events (required, type-enforced)
   */
  handlers: {
    [K in keyof T['client']]: (payload: T['client'][K]) => void
  };

  /**
   * Optional cleanup function called when connection ends
   */
  unsubscribe?: () => void;
}

/**
 * Server-side channel interface (passed to onSubscribe callback)
 * - Tied to single WebSocket connection
 * - Can SUBSCRIBE to client events (from this connection)
 * - Can SEND server events (to this connection)
 *
 * Note: This is an interface (not Zod) because it contains methods
 */
export interface ServerChannel<T extends { client: Record<string, Record<string, unknown>>; server: Record<string, Record<string, unknown>> }> {
  /**
   * Unique channel instance ID
   */
  readonly id: string;

  /**
   * Send server event to this connection
   */
  send<K extends keyof T['server']>(
    event: K,
    payload: T['server'][K]
  ): void;
}
